/*
 Generated by typeshare 1.6.0
*/

export interface ContentDto {
	id: number;
	source_id: number;
	title: string;
	url: string;
	date_published: string;
	date_retrieved: string;
}

export enum SourceKind {
	RSS = "RSS",
	WEB = "WEB",
}

