name: 'test-on-pr'
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Rust @nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: install dependencies (ubuntu only)
        # consult https://packages.ubuntu.com/
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglib2.0-0 libglib2.0-dev libsoup2.4-dev libsoup2.4-cil-dev libavahi-gobject0 libavahi-gobject-dev libwebkit2gtk-4.0-dev libappindicator3-dev libappindicator3-0.1-cil-dev librsvg2-dev patchelf
      - name: install Tauri CLI
        run: yarn global add typescript @tauri-apps/cli # because not root
      - name: install frontend dependencies
        run: cd ./stories && yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './stories'
