name: 'test-on-pr'
on: [pull_request]

jobs:
  test-tauri:
    strategy:
        fail-fast: false
        matrix:
          include:
            - platform: 'macos-latest' # for Arm based macs (M1 and above).
              args: '--target aarch64-apple-darwin'
            - platform: 'macos-latest' # for Intel based macs.
              args: '--target x86_64-apple-darwin'
            - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
              args: ''
            # Windows requires additional dependencies and also doesn't run in Workflows
            # - platform: 'windows-latest'
            #   args: ''
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust @nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: install dependencies (ubuntu only)
        # consult https://packages.ubuntu.com/
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglib2.0-0 libglib2.0-dev libglib2.0-dev-bin libsoup-3.0-dev libavahi-gobject0 libavahi-gobject-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install Tauri CLI
        run: yarn global add typescript @tauri-apps/cli # because not root

      - name: install frontend dependencies
        run: cd ./stories && yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './stories'
